name: Build and Publish Docker image

# Trigger on pushes to astria branch, new semantic version tags, and pull request updates
on:
  workflow_dispatch:
  push:
    branches:
      - "astria"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
  # trigger on pull request updates when target is `astria` branch
  pull_request:
    branches:
      - "astria"

jobs:
  # lint and test jobs came from Metro
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    needs: lint
    uses: ./.github/workflows/test.yml

  build-and-publish-latest:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      # Checking out the repo
      - uses: actions/checkout@v3
      # Setting up Go
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.20.x" # The Go version to download (if necessary) and use.
      - run: go version

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Generate correct tabs and labels
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/astriaorg/metro
          tags: |
            type=ref,event=pr
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=sha
            # set latest tag for `astria` branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'astria') }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./docker/Dockerfile.test
          context: .
          # It takes over 30 minutes to build the arm image right now, so we only build it on tags which is what we use for releases.
          platforms: ${{ contains(github.ref, 'refs/tags/v') && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          # push: true
          push: false
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
